# Generated by Django 5.2.14 on 2026-05-25 21:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_alter_producto_categoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('tamano', models.CharField(blank=True, choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=20, null=True)),
                ('tipo_leche', models.CharField(blank=True, choices=[('Entera', 'Entera'), ('Descremada', 'Descremada'), ('Almendra', 'Almendra'), ('Avena', 'Avena'), ('Sin Leche', 'Sin Leche')], max_length=20, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.producto')),
            ],
        ),
    ]
