# Generated by Django 5.2.14 on 2026-06-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_itempedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='tiene_tamano',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='categoria',
            name='tiene_tipo_leche',
            field=models.BooleanField(default=False),
        ),
    ]
