# Generated by Django 5.2.14 on 2026-06-16 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_categoria_tiene_tamano_categoria_tiene_tipo_leche'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='precio_unitario',
            field=models.IntegerField(default=0),
        ),
    ]
